apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- pdb.yaml
namespace: chuck
replicas:
- count: 3
  name: webapp
labels:
- includeSelectors: true
  includeTemplates: true
  pairs:
    app: webapp
patches:
  - path: patch-deployment.yaml
    target:
      kind: Deployment
      name: webapp
