apiVersion: v1
kind: ConfigMap
metadata:
  name: default.conf
  labels:
    app: webapp
data:
  default.conf.template: |
    server {
        listen 80;
        keepalive_timeout 10;
        server_name localhost;

        location / {
            root /usr/share/nginx/html;
            index index.html;
            set $VERSION "$APP_VERSION";
            set $BG "$BG_COLOR";
            set $NODENAME "$NODE_NAME";
        }

        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
            root /usr/share/nginx/html;
        }

        ssi on;
        ssi_silent_errors off;
        ssi_last_modified off;
    }
