apiVersion: v1
kind: ConfigMap
metadata:
  name: html
  labels:
    app: webapp
data:
  index.html: |
    <!DOCTYPE html>
    <html>
     <head>
     <meta name="viewport" content="width=device-width, initial-scale=1">
     <meta http-equiv="refresh" content="30">
     <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
     <meta http-equiv="Pragma" content="no-cache" />
     <meta http-equiv="Expires" content="0" />
     <title>Webapp</title>
     <style>
       body {
         font-family: Tahoma, Verdana, Arial, sans-serif;
         background-color: <!--# echo var="BG" default="cornflowerblue" -->;
         text-align: center;
       }
     </style>
     </head>
     <body>
      <h1>Welcome to version <!--# echo var="VERSION" default="v0.0.0" --> </h1>
      <!--# echo var="HOSTNAME" default="unknown" --> on <!--# echo var="NODENAME" default="unknown" -->
     </body>
    </html>
