apiVersion: apps/v1
kind: Deployment
metadata:
    name: webapp
    annotations:
      kubectl.kubernetes.io/default-container: nginx
      reloader.stakater.com/auto: "true"
      #cleanup.kyverno.io/ttl: 2m
    labels:
      app: webapp
      version: v1.0.0
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: webapp
      version: v1.0.0
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: webapp
        version: v1.0.0
        sidecar.istio.io/inject: "false"
    spec:
      automountServiceAccountToken: false
      enableServiceLinks: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "100Mi"
            cpu: "100m"
        readinessProbe:
          httpGet:
            path: /
            port: http
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 1
          failureThreshold: 3
          successThreshold: 1
        livenessProbe:
          httpGet:
            path: /
            port: http
            scheme: HTTP
          initialDelaySeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
          successThreshold: 1
        volumeMounts:
        - mountPath: /usr/share/nginx/html/index.html
          name: html
          subPath: index.html
        - mountPath: /etc/nginx/conf.d
          name: config
      volumes:
      - name: html
        configMap:
          name: html
      - name: config
        configMap:
          name: default.conf
