apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap-homepage.yaml
- configmap-nginx.yaml
- deployment.yaml
- service.yaml
# - network-policy.yaml
# - pdb.yaml
# - scaledobject-defaultingress.yaml
namespace: chuck
replicas:
- count: 1
  name: webapp
labels:
- includeSelectors: true
  includeTemplates: true
  pairs:
    app: webapp
